codecov:
  branch: default
coverage:
  status:
    project:
      default:
        base: pr # Only post a status to pull requests
        informational: true # Don't block PRs based on coverage stats (yet?)
ignore:
  - "/src/examples"
  - "/src/Qt/demo"
  - "/thirdparty/jsoncpp/*.cpp"
  - "/thirdparty/jsoncpp/json/*.h"
  - "/doc"
  - "/cmake"
  - "/*.md"
