codecov:
  branch: default
coverage:
  status:
    project:
      default:
        base: pr # Only post a status to pull requests
        informational: true # Don't block PRs based on coverage stats (yet?)
ignore:
  - "/examples"
  - "/bindings"
  - "/thirdparty/jsoncpp"
  - "/doc"
  - "/cmake"
  - "/*.md"
  - "bindings"
  - "src/openshot_autogen"
